### ISSUE TITLE
Only allow GET and HEAD requests

### ISSUE THREAD

**Issue by apburnes** [cloud-gov/pages-proxy#187]
To improve security posture, only allow `GET` and `HEAD` request methods in the proxy.

## Acceptance Criteria

- [ ] Returns a `405` status code if any other method is requested

**Comment by svenaas** [comment]
This is a good move. You're too quick, @apburnes :)

**Comment by svenaas** [comment]
Is the `405` a specific requirement? The `limit_except` directive can do this pretty tidily but I think it returns a `403`.

**Comment by apburnes** [comment]
@svenaas `405` is `Method Not Allowed` while a `403` is `Forbidden` where returning the status could be interpreted as insufficient rights to a resource. I went with `405` to return the more semantic status.

**Comment by svenaas** [comment]
I agree that's better. It's a little weird that `limit_except` doesn't seem to provide a way to specify the response code for a particular use. That reduces the utility of the directive.
